### ISSUE TITLE
Research Tools for All Businesses

### ISSUE THREAD

**Issue by BoyerChris** [BoyerChris/Team-22-Senior-Design-Project#5]

**Comment by stanileh** [comment]
After 9/26 Meeting did some generic googling and researching online into tools.

**Comment by stanileh** [comment]
9/27

Planning to focus on researching and categorizing tools that I believe are most common / necessary among the majority of modern day companies.

**Comment by stanileh** [comment]
**9/27-29**

Conducted further research Friday through Sunday, the storm Friday cut our power so I had to work elsewhere for the time being.

Although, I did find out some valuable information regarding some very common tools business uses nowadays, that can be very helpful for the development of our checklist, as well as some slightly less common tools, which I also documented. 

[Research Tools for All Businesses \[STANILEH\].docx](https://github.com/user-attachments/files/17191465/Research.Tools.for.All.Businesses.STANILEH.docx)
